### ISSUE TITLE
Faster way to read fixed-width files in R

### ISSUE THREAD

**Issue by rafapereirabr** [ajdamico/SAScii#1]
Hi Anthony.

I was wondering if there would be a way to improve the speed of SAScii by using `read_fwf()` from package `readr` or using `laf_open_fwf()` from package `LaF` instead of `read.fwf`. There is an interesting [discussion about a these packages in this SO thread](http://stackoverflow.com/questions/24715894/faster-way-to-read-fixed-width-files-in-r).

ps. Thank you for developing SAScii. This is a great package and I'm sure many users in the R community are grateful for it!

**Comment by ajdamico** [comment]
hi, `?parse.SAScii()` can feed other functions.  i'm not eager to change what's on cran.  thanks!

**Comment by rafapereirabr** [comment]
ok! Cheers !
