### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by markgsheppard** [ajdamico/SAScii#10]
Using the following code, I get the following error.
Any updates on code for previous versions?
Thanks 

```{r}

{install.packages("SAScii", dependencies = TRUE) }
Warning in install.packages :
  package ‘SAScii’ is not available for this version of R

```

**Comment by ajdamico** [comment]
hi Mark, if you're stuck using a really old version of R and not allowed to update your software, you could fork the project, change this line, and use `remotes::install_github("markgsheppard/SAScii")` to get it loaded


https://github.com/cran/SAScii/blob/master/DESCRIPTION#L11
