### ISSUE TITLE
Reading in NHIS survey data with read.SAScii

### ISSUE THREAD

**Issue by gbrlrz017** [ajdamico/SAScii#3]
Hi, I have a question about one of your examples in the documentation for `read.SAScii`. 

Here's the verbatim example: 

> NHIS.11.samadult.SAS.read.in.instructions <- 
>  "ftp://ftp.cdc.gov/pub/Health_Statistics/NCHS/Program_Code/NHIS/2011/SAMADULT.sas"
> NHIS.11.samadult.file.location <- 
>  "ftp://ftp.cdc.gov/pub/Health_Statistics/NCHS/Datasets/NHIS/2011/samadult.zip"
> # store the NHIS file as an R data frame!
> 
> NHIS.11.samadult.df <- 
>  read.SAScii ( 
>    NHIS.11.samadult.file.location , 
>    NHIS.11.samadult.SAS.read.in.instructions , 
>    zipped = T, )
> # or store the NHIS SAS import instructions for use in a
> # read.fwf function call outside of the read.SAScii function
> 
> NHIS.11.samadult.sas <- parse.SAScii( NHIS.11.samadult.SAS.read.in.instructions )
> # save the data frame now for instantaneous loading later
> 
> save( NHIS.11.samadult.df , file = "NHIS.11.samadult.data.rda" )

I am trying to do the same with the 2010 version of the survey. However, with both this 2011 file and the 2010 file I get the error `Error in toupper(SASinput) : invalid multibyte string 533` with the `read.SAScii` call. What can you make of it? Thanks!

**Comment by ajdamico** [comment]
hi, encoding.  it is a waste of your time to re-do this on individual files.  use the quick-start block at the top of

https://github.com/ajdamico/asdfree/blob/master/National%20Health%20Interview%20Survey/download%20all%20microdata.R#L8-L13

and everything will be imported automatically.  thanks and keep in touch

**Comment by gbrlrz017** [comment]
Hey, thanks for this! I have the data loaded and ready to work with these next few weeks!
