### ISSUE TITLE
Add support for different file encodings

### ISSUE THREAD

**Issue by leofontenelle** [ajdamico/SAScii#5]
The encoding of a SAS input file may be different from the file system encoding. Thus, trying parse.SAScii() in a system (e.g. Linux and, I guess, Mac OS X) with UTF-8 for file encoding will fail with an input file encoded in e.g. ISO-8859-1. This could be remedied by adding a "encoding" parameter in parse.SAScii() (and maybe in read.SAScii() as well), and passing this parameter to the readLines() call.

**Comment by ajdamico** [comment]
sorry, `SAScii` on cran won't change unless there's a major bug

**Comment by leofontenelle** [comment]
Could you please update SAScii on GitHub, then? I hope this [patch](https://github.com/ajdamico/SAScii/files/302482/encoding.patch.zip) helps.

**Comment by ajdamico** [comment]
sorry, no.  you can fork the project if you need to..
