### ISSUE TITLE
NAMESPACE files are now required!

### ISSUE THREAD

**Issue by olyerickson** [ajdamico/SAScii#6]
R 3.0.0 and beyond requires packages to include NAMESPACE files. See discussion here:

https://stackoverflow.com/questions/17196225/error-a-namespace-file-is-required

**Comment by ajdamico** [comment]
what error are you facing?

**Comment by olyerickson** [comment]
It's precisely the error in that link:
```
ERROR: a 'NAMESPACE' file is required
```
The problem is solved when I re-package as described in that link.

**Comment by ajdamico** [comment]
you're getting that error when installing from CRAN?

**Comment by olyerickson** [comment]
Not, I installed from github. Is CRAn version more current?

**Comment by ajdamico** [comment]
hi, they're identical and i'd prefer to keep what's in this repo matching what's on cran.  let me know if the cran version fails.  thanks

**Comment by olyerickson** [comment]
Installing from CRAN works... Thanks!
