### ISSUE TITLE
Error in firstline:lastline : NA/NaN

### ISSUE THREAD

**Issue by JsthcitPizifly** [ajdamico/SAScii#8]
Hello, I've got a data file from https://www.cdc.gov/nchs/nhis/nhis_2014_data_release.htm, "[ASCII data zip icon[ZIP – 1.1 MB]](https://ftp.cdc.gov/pub/Health_Statistics/NCHS/Datasets/NHIS/2014/familyxx.zip)".

**Comment by JsthcitPizifly** [comment]
and I use "data <- parse.SAScii("/Users/xxx/Desktop/familyxx.dat")", got error(Error in firstline:lastline : NA/NaN). What's wrong?

**Comment by JsthcitPizifly** [comment]
and I wonder if SAScii can decode this ASCII file？[ASCII data zip icon[ZIP – 1.1 MB]](https://ftp.cdc.gov/pub/Health_Statistics/NCHS/Datasets/NHIS/2014/familyxx.zip)

**Comment by JsthcitPizifly** [comment]
thanks a lot

**Comment by ajdamico** [comment]
hi, `parse.SAScii` accepts `.sas` files
