### ISSUE TITLE
toupper(SASinput) error in parse.SAScii

### ISSUE THREAD

**Issue by kamermanpr** [ajdamico/SAScii#9]
Hi, your package has been a lifesaver and significantly streamlined my code. However, I encountered the following error when running the `read.SAScii()` function: _Error in toupper(SASinput) : invalid multibyte string 1234_. 

Looking through the source code, I narrowed the error down to the `toupper()` function call on line 10 and/or line 27 of the `parse.SAScii()` helper function. I figure it must have something to do with the text encoding in the SAS import instructions I was supplied with, which `toupper()` fails to handle. 

I found a fix though, and that was to change `toupper()` from _base R_ to `stri_trans_toupper()` from the _stringi_ package. Whatever the issue was with `toupper()`,  `stri_trans_toupper()` overcame the issue. 

I am running:
R version 4.2.0 (2022-04-22) -- "Vigorous Calisthenics"
Platform: x86_64-apple-darwin17.0 (64-bit)

Code:
```
# Load package
library(SAScii)

# File/instruction locations
instructions_2008 <- 'ftp://ftp.cdc.gov/pub/Health_Statistics/NCHS/Program_Code/NHIS/2008/SAMADULT.sas'
file_location_2008 <- 'ftp://ftp.cdc.gov/pub/Health_Statistics/NCHS/Datasets/NHIS/2008/samadult.zip'

# Import data
data_2008 <- read.SAScii(fn = file_location_2008,
+                        sas_ri = instructions_2008,
+                        zipped = TRUE)

Error in toupper(SASinput) : invalid multibyte string 1234
```

**Comment by ajdamico** [comment]
nice to hear from you!  i'd rather keep `library(SAScii)` frozen but this code from asdfree.com might be helpful

	devtools::install_github("ajdamico/lodown")
	library(lodown)
	nhis_cat <- get_catalog( "nhis" , output_dir = tempdir() )
	lodown( "nhis" , subset( nhis_cat , year == 2008 & type == 'samadult' ) )
	samadult_df <- readRDS( paste0( tempdir() , "/2008/samadult.rds" ) )
	head(samadult_df)

**Comment by kamermanpr** [comment]
No worries, and thanks for pointing me at an alternative solution.

Best regards
Peter
